version: '3.5'

# https://github.com/khezen/compose-postgres:
services:
  postgres-db:
    container_name: postgres_otus_hw_6
    image: postgres
    volumes:
      - ../hw_1/data:/tmp/input_data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_otus_hw_6
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres-db
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-db:
  pgadmin:
